# Generated by Django 3.0.5 on 2020-05-29 09:26

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, height_field=500, upload_to='', verbose_name=django.contrib.auth.models.User, width_field=500),
            preserve_default=False,
        ),
    ]
