# Generated by Django 3.0.5 on 2020-05-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0003_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image1',
            field=models.ImageField(default='sld4.jpg', upload_to='profile_pics'),
        ),
    ]
