# Generated by Django 3.0.5 on 2020-07-05 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0005_auto_20200705_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='post',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='post',
            name='message',
        ),
        migrations.RemoveField(
            model_name='post',
            name='phonenumber',
        ),
    ]
